#if defined _bonus_round_win_panel_event_included
 #endinput
#endif
#define _bonus_round_win_panel_event_included

#define TEAM_UNASSIGNED 0

#define EVENT_ROUND_WIN "dod_round_win"
#define EVENT_ROUND_START "dod_round_start"
#define EVENT_WIN_PANEL "dod_win_panel"
#define EVENT_PLAYER_SPAWN "player_spawn"

#define KEY_TEAM "team"
#define KEY_USER_ID "userid"
#define KEY_SHOW_TIMER_DEFEND "show_timer_defend"
#define KEY_SHOW_TIMER_ATTACK "show_timer_attack"
#define KEY_TIMER_TIME "timer_time"
#define KEY_FINAL_EVENT "final_event"
#define KEY_CATEGORY_LEFT "category_left"
#define KEY_LEFT_1 "left_1"
#define KEY_LEFT_SCORE_1 "left_score_1"
#define KEY_LEFT_2 "left_2"
#define KEY_LEFT_SCORE_2 "left_score_2"
#define KEY_LEFT_3 "left_3"
#define KEY_LEFT_SCORE_3 "left_score_3"
#define KEY_CATEGORY_RIGHT "category_right"
#define KEY_RIGHT_1 "right_1"
#define KEY_RIGHT_SCORE_1 "right_score_1"
#define KEY_RIGHT_2 "right_2"
#define KEY_RIGHT_SCORE_2 "right_score_2"
#define KEY_RIGHT_3 "right_3"
#define KEY_RIGHT_SCORE_3 "right_score_3"
